"use client"
import { useCallback, useEffect, useRef, useState } from "react"
import Link from "next/link"
import { RefreshCw, BarChart3, ArrowLeft, Users, CheckCircle2, CalendarDays, Target } from "lucide-react"
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts"
import { useReducedMotion } from "framer-motion"
import { AdminLoading } from "@/components/admin/admin-loading"
import { TrendChart, ServiceDemand } from "@/components/admin/dashboard/charts"
import { StatusBadge } from "@/components/admin/dashboard/status-badge"
import { RecentLeads } from "@/components/admin/dashboard/recent-leads"
import type { DashboardLead } from "@/components/admin/dashboard/types"
type Analytics={totalLeads:number;todayLeads:number;activeLeads:number;convertedLeads:number;closedLeads:number;conversionRate:number;thisMonthLeads:number;lastMonthLeads:number;growthPercentage:number|null;latestLeads:DashboardLead[];monthlyLeads:{date:string;month:string;total:number}[];serviceStats:{_id:string;total:number}[];sourceStats:{_id:string;total:number}[];statusStats:{name:string;total:number}[];dailyTrend:{date:string;label:string;total:number}[];current30Days:number;previous30Days:number;leadTrendPercentage:number|null;updatedAt:string}
const card="min-w-0 rounded-2xl border border-border bg-card p-5 shadow-sm"
export default function AnalyticsPage(){
 const [data,setData]=useState<Analytics|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("")
 const controller=useRef<AbortController|null>(null),reduced=useReducedMotion()
 const load=useCallback(async()=>{controller.current?.abort();const request=new AbortController();controller.current=request;setBusy(true);const timeout=setTimeout(()=>request.abort("timeout"),20000)
 try{const response=await fetch("/api/analytics",{cache:"no-store",signal:request.signal});if(!response.ok)throw Error(response.status===401||response.status===403?"Please sign in again to view analytics.":"Unable to load analytics. Please retry.");const result=await response.json();if(!result.success)throw Error("Unable to load analytics. Please retry.");if(!request.signal.aborted){setData(result);setError("")}}
 catch(e){if(!request.signal.aborted||request.signal.reason==="timeout")setError(request.signal.reason==="timeout"?"Analytics took too long to respond. Please retry.":e instanceof Error?e.message:"Unable to load analytics.")}
 finally{clearTimeout(timeout);if(!request.signal.aborted||request.signal.reason==="timeout")setBusy(false)}
 },[])
 useEffect(()=>{void load();return()=>controller.current?.abort()},[load])
 if(!data&&!error)return <AdminLoading title="Loading Analytics" description="Calculating your lead trends, conversions and service demand..."/>
 return <div className="mx-auto max-w-[1600px] space-y-5 pb-8 text-foreground"><header className={`${card} flex flex-wrap items-center justify-between gap-4`}><div><Link href="/admin/dashboard" className="inline-flex items-center gap-1 text-xs text-muted-foreground"><ArrowLeft size={14}/>Dashboard</Link><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Analytics Dashboard</h1><p className="mt-2 text-sm text-muted-foreground">Real lead performance and acquisition insights / India time (IST)</p>{data&&<p className="mt-2 text-xs text-muted-foreground">Updated {new Date(data.updatedAt).toLocaleTimeString()}</p>}</div><button onClick={()=>void load()} disabled={busy} aria-label="Refresh analytics" title="Refresh analytics" className="flex h-11 w-11 items-center justify-center rounded-xl border border-border bg-muted disabled:opacity-50"><RefreshCw size={18} className={busy?"animate-spin":""}/></button></header>
 {error&&<div role="alert" className="flex min-h-48 flex-col items-center justify-center gap-3 rounded-2xl border border-destructive/30 bg-card p-6 text-center"><BarChart3 className="text-destructive" size={28}/><p>{error}</p>{data&&<p className="text-xs text-muted-foreground">Showing the last successfully loaded data.</p>}<button disabled={busy} className="min-h-11 rounded-xl bg-accent px-5 text-sm font-semibold text-accent-foreground" onClick={()=>void load()}>Retry analytics</button></div>}
 {data&&<><section aria-label="Analytics summary" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total leads",data.totalLeads,Users],["New today",data.todayLeads,CalendarDays],["Won / installed",data.convertedLeads,CheckCircle2],["Conversion",`${data.conversionRate}%`,Target]].map(([label,value,Icon])=>{const Glyph=Icon as typeof Users;return <div className={card} key={String(label)}><div className="flex items-center justify-between gap-2"><p className="text-xs text-muted-foreground">{String(label)}</p><Glyph size={18} className="text-brand-green"/></div><p className="mt-3 text-3xl font-bold">{String(value)}</p></div>})}</section>
 <section className="grid items-start gap-5 xl:grid-cols-2"><div className={card}><h2 className="text-lg font-bold">30-day lead trend</h2><TrendChart trend={{rows:data.dailyTrend,current:data.current30Days,previous:data.previous30Days,change:data.leadTrendPercentage}}/></div><div className={card}><h2 className="text-lg font-bold">Monthly lead growth</h2><p className="mt-2 text-xs text-muted-foreground">Last 12 calendar months. Current month is partial.</p><p className="mt-3 text-sm">{data.thisMonthLeads} this month / {data.lastMonthLeads} last month <span className="font-semibold text-brand-green">{data.growthPercentage===null?" / No previous data":` / ${data.growthPercentage>0?"+":""}${data.growthPercentage}%`}</span></p><div className="mt-4 h-64" role="img" aria-label="Monthly lead totals for the last twelve months"><ResponsiveContainer width="100%" height="100%"><BarChart accessibilityLayer data={data.monthlyLeads} margin={{left:-20,right:5}}><CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 3"/><XAxis dataKey="month" minTickGap={20} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><YAxis allowDecimals={false} tick={{fill:"var(--muted-foreground)",fontSize:11}}/><Tooltip contentStyle={{background:"var(--popover)",color:"var(--popover-foreground)",border:"1px solid var(--border)",borderRadius:12}}/><Bar name="Leads" dataKey="total" fill="var(--chart-1)" radius={[5,5,0,0]} isAnimationActive={!reduced}/></BarChart></ResponsiveContainer></div><details className="text-xs text-muted-foreground"><summary className="cursor-pointer py-2">View monthly data</summary>{data.monthlyLeads.map(row=><p key={row.date} className="flex justify-between py-1"><span>{row.month}</span><span>{row.total}</span></p>)}</details></div></section>
 <section className="grid gap-5 lg:grid-cols-2"><div className={card}><h2 className="text-lg font-bold">Service demand</h2><ServiceDemand metrics={{total:data.totalLeads,services:data.serviceStats}}/></div><div className={card}><h2 className="text-lg font-bold">Lead sources</h2><p className="mt-2 text-xs text-muted-foreground">Enquiries by acquisition channel</p><div className="mt-4 space-y-4">{data.sourceStats.map(row=><div key={row._id||"unknown"}><div className="flex justify-between text-sm"><span>{row._id||"Not recorded"}</span><strong>{row.total}</strong></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-accent" style={{width:`${data.totalLeads?row.total/data.totalLeads*100:0}%`}}/></div></div>)}</div>{!data.sourceStats.length&&<p className="py-8 text-sm text-muted-foreground">No acquisition data yet.</p>}</div></section>
 <section className={card}><h2 className="text-lg font-bold">Lead status distribution</h2><p className="mt-2 text-xs text-muted-foreground">Conversion = won or installed leads divided by all leads. {data.activeLeads} active / {data.closedLeads} closed or cancelled.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.statusStats.map(row=><div key={row.name} className="flex items-center justify-between gap-3 rounded-xl bg-muted/40 p-3"><StatusBadge status={row.name}/><strong>{row.total}</strong></div>)}</div></section><section className={card}><h2 className="text-lg font-bold">Recent leads</h2><RecentLeads leads={data.latestLeads}/></section></>}
 </div>
}
