"use client"
import { useEffect, useState } from "react"
import { action, api, control, ErrorNotice, format, MetricCard, Panel } from "./shared"
type SpeedData = { testedAt: string; scores: Record<string, number | null>; lab: Record<string, string | null>; field: Record<string, { percentile?: number; category?: string }> | null; issues: { id: string; title: string; recommendation: string; severity: string; savingsMs: number | null; savingsBytes: number | null; resources: string[]; detail: string | null }[] }
function SpeedCard({ strategy, url }: { strategy: string; url: string }) {
  const [data, setData] = useState<SpeedData | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false)
  const endpoint = `/api/admin/website-analytics/pagespeed?strategy=${strategy}&url=${encodeURIComponent(url)}`
  useEffect(() => { const c = new AbortController(); setData(null); setError(""); api<{ data: SpeedData | null }>(endpoint, "GET", c.signal).then(r => setData(r.data)).catch(e => { if (e.name !== "AbortError") setError(e.message) }); return () => c.abort() }, [endpoint])
  async function run() { setBusy(true); setError(""); try { setData((await api<{ data: SpeedData }>(endpoint, "POST")).data) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <Panel title={`${strategy === "mobile" ? "Mobile" : "Desktop"} performance`}><div className="space-y-4"><button className={action} disabled={busy} onClick={run}>{busy ? "Testing… may take 90 seconds" : "Run New Test"}</button>{error && <ErrorNotice error={error}/>}{!data ? <p className="text-sm text-muted-foreground">No saved test. Run a test to fetch current Lighthouse results.</p> : <>
    <p className="text-xs text-muted-foreground">Last tested: {new Date(data.testedAt).toLocaleString()}</p><div className="grid grid-cols-2 gap-3">{Object.entries(data.scores).map(([key, value]) => <MetricCard key={key} label={key.replaceAll("-", " ")} value={value}/>)}</div>
    <h3 className="font-semibold">Lab data · Lighthouse</h3><dl className="space-y-2 text-sm">{Object.entries(data.lab).map(([key, value]) => <div className="flex flex-wrap justify-between gap-2" key={key}><dt>{key.replaceAll("-", " ")}</dt><dd>{format(value)}</dd></div>)}</dl>
    <h3 className="font-semibold">Real-user field data · CrUX</h3><p className="text-xs text-muted-foreground">Page-level rolling field data is separate from this lab test and the analytics date range.</p>{data.field && Object.keys(data.field).length ? <dl className="space-y-2 text-sm">{["LARGEST_CONTENTFUL_PAINT_MS", "INTERACTION_TO_NEXT_PAINT", "CUMULATIVE_LAYOUT_SHIFT_SCORE"].map(key => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{data.field?.[key]?.percentile === undefined ? "N/A" : key === "CUMULATIVE_LAYOUT_SHIFT_SCORE" ? format(data.field[key].percentile! / 100) : `${format(data.field[key].percentile)} ms`} · {data.field?.[key]?.category || "Unavailable"}</dd></div>)}</dl> : <p className="text-sm text-muted-foreground">Not enough real-user data available.</p>}
    <h3 className="font-semibold">Lighthouse issues</h3>{!data.issues.length && <p className="text-sm">No scored issues returned.</p>}{data.issues.map(issue => <details key={issue.id} className="rounded-xl border border-border p-3 text-sm"><summary className="cursor-pointer">{issue.title} · {issue.severity}</summary><p className="mt-2 break-words text-muted-foreground">{issue.recommendation}</p><p className="mt-2">{issue.detail || ""} · Estimated savings: {format(issue.savingsMs)} ms / {format(issue.savingsBytes)} bytes</p>{issue.resources.map((resource, i) => <p className="mt-1 break-all text-xs" key={i}>{resource}</p>)}</details>)}
  </>}<p className="text-xs text-muted-foreground">Five-minute test cooldown per device. Lighthouse SEO measures technical checks, not rankings or indexing.</p></div></Panel>
}
export function Performance({ url = "/" }: { url?: string }) { return <div className="grid min-w-0 gap-5 xl:grid-cols-2"><SpeedCard key={`mobile:${url}`} strategy="mobile" url={url}/><SpeedCard key={`desktop:${url}`} strategy="desktop" url={url}/></div> }
type IndexResponse = { paths: string[]; data: { sitemap?: { path: string; lastSubmitted?: string; lastDownloaded?: string; warnings?: string; errors?: string; isPending?: boolean }[] } | null }
export function IndexMonitor() {
  const [paths, setPaths] = useState<string[]>([]), [sitemaps, setSitemaps] = useState<NonNullable<IndexResponse["data"]>["sitemap"]>([]), [url, setUrl] = useState("/"), [data, setData] = useState<Record<string, string | null> | null>(null), [checked, setChecked] = useState<string | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false)
  useEffect(() => { const c = new AbortController(); api<IndexResponse>("/api/admin/website-analytics/indexing", "GET", c.signal).then(r => { setPaths(r.paths); setSitemaps(r.data?.sitemap || []) }).catch(e => { if (e.name !== "AbortError") setError(e.message) }); return () => c.abort() }, [])
  useEffect(() => { const c = new AbortController(); setData(null); setChecked(null); api<{ data: Record<string, string | null> | null; fetchedAt: string | null }>(`/api/admin/website-analytics/indexing?url=${encodeURIComponent(url)}`, "GET", c.signal).then(r => { setData(r.data); setChecked(r.fetchedAt) }).catch(e => { if (e.name !== "AbortError") setError(e.message) }); return () => c.abort() }, [url])
  async function inspect() { setBusy(true); setError(""); try { const r = await api<{ data: Record<string, string | null>; fetchedAt: string }>(`/api/admin/website-analytics/indexing?url=${encodeURIComponent(url)}`, "POST"); setData(r.data); setChecked(r.fetchedAt) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <div className="space-y-5">{error && <ErrorNotice error={error}/>}<Panel title="Important URL monitor"><p className="mb-4 text-sm text-muted-foreground">Inspect actual public pages. Results are cached for 24 hours. This is not Search Console’s complete indexing report.</p><div className="flex flex-wrap gap-3"><select disabled={busy} className={`${control} min-w-0 max-w-full flex-1`} aria-label="URL to inspect" value={url} onChange={e => setUrl(e.target.value)}>{(paths.length ? paths : ["/"]).map(p => <option key={p}>{p}</option>)}</select><button className={action} disabled={busy} onClick={inspect}>{busy ? "Checking…" : "Check Index Status"}</button></div>{checked && <p className="mt-3 text-xs text-muted-foreground">Last checked: {new Date(checked).toLocaleString()}</p>}{data ? <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">{Object.entries(data).map(([key, value]) => <div key={key}><dt className="text-muted-foreground">{key}</dt><dd className="break-all">{format(value)}</dd></div>)}</dl> : <p className="mt-4 text-sm">No saved inspection for this URL.</p>}</Panel><Panel title="Sitemaps">{!sitemaps?.length ? <p className="text-sm text-muted-foreground">No sitemap data available.</p> : sitemaps.map(s => <dl key={s.path} className="mb-3 space-y-1 rounded-xl border border-border p-3 text-sm"><dt className="break-all font-medium">{s.path}</dt><dd>Last submitted: {s.lastSubmitted || "N/A"}</dd><dd>Last downloaded: {s.lastDownloaded || "N/A"}</dd><dd>Warnings: {s.warnings ?? "N/A"} · Errors: {s.errors ?? "N/A"} · {s.isPending ? "Pending" : "Processed"}</dd></dl>)}</Panel></div>
}
