import Image from "next/image"
import Link from "next/link"
import { Facebook, Instagram, Mail, MapPin, Phone, Youtube } from "lucide-react"
import { FaWhatsapp } from "react-icons/fa"

const groups = [{ title: "Company", links: [["Home", "/home"], ["Services", "/services"],["About", "/about"], ["Gallery", "/gallery"], ["Blog", "/blog"], ["Contact", "/contact"]] }, { title: "Solutions", links: [["CCTV surveillance", "/services/cctv-surveillance"], ["Biometric attendance", "/services/biometric-attendance"], ["Networking", "/services/networking-solutions"], ["Home automation", "/services/home-automation"],["Wifi & Mesh Networking", "/services/wifi-mesh-networking"],["IT Support & AMC Solutions", "/services/it-support-amc"]] }, { title: "Support", links: [["FAQs", "/faq"], ["Request consultation", "/contact"], ["Call us", "tel:+919872133840"], ["WhatsApp", "https://wa.me/919872133840"]] }]
const socials = [{ Icon: Youtube, href: "https://www.youtube.com/@visionsecure_tech", label: "YouTube", color: "hover:text-destructive" }, { Icon: Instagram, href: "https://www.instagram.com/visionsecure_tech/", label: "Instagram", color: "hover:text-status-pink" }, { Icon: Facebook, href: "https://www.facebook.com/profile.php?id=61584897029759", label: "Facebook", color: "hover:text-brand-ink" }, { Icon: FaWhatsapp, href: "https://wa.me/919872133840", label: "WhatsApp", color: "hover:text-brand-green" }]

export function Footer() { return <footer className="border-t border-border bg-secondary text-muted-foreground"><div className="page-container grid gap-10 py-14 md:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><Image src="/images/Visionsecuretech_logo.png" alt="VisionSecure Smart Technologies" width={230} height={60} className="h-10 w-auto dark:rounded-md dark:bg-white dark:p-1" /><p className="mt-5 max-w-xs text-sm leading-6">Professional security, networking and smart technology solutions designed around your real-world requirements.</p><div className="mt-6 flex gap-3">{socials.map(({ Icon, href, label, color }) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" aria-label={label} className={`rounded-lg border border-border bg-card p-2.5 text-muted-foreground transition hover:-translate-y-0.5 hover:border-primary ${color}`}><Icon size={18} /></a>)}</div></div>{groups.map(group => <div key={group.title}><h2 className="mb-4 text-sm font-semibold uppercase tracking-[.14em] text-foreground">{group.title}</h2><ul className="space-y-3">{group.links.map(([label, href]) => <li key={label}><Link href={href} className="text-sm transition hover:text-brand-ink">{label}</Link></li>)}</ul></div>)}<div className="md:col-span-2 lg:col-span-4 grid gap-4 border-t border-border pt-7 text-sm sm:grid-cols-3"><a className="flex items-center gap-2" href="tel:+919872133840"><Phone size={16} className="text-brand-green" />+91 98721-33840</a><a className="flex items-center gap-2" href="mailto:info@visionsecuretech.in"><Mail size={16} className="text-brand-green" />info@visionsecuretech.in</a><span className="flex items-center gap-2"><MapPin size={16} className="text-brand-green" />Lucknow, Uttar Pradesh</span></div></div><div className="border-t border-border"><div className="page-container flex flex-col justify-between gap-2 py-5 text-xs sm:flex-row"><span>© {new Date().getFullYear()} VisionSecure Smart Technologies.</span><span>Security and IT solutions with professional support.</span></div></div></footer> }
