import type { LucideIcon } from "lucide-react"
import { Camera, Fingerprint, Network, Radio, Wrench, Server, Video, KeyRound, House, ShieldCheck, BellRing, Speaker } from "lucide-react"

export type Service = { slug: string; title: string; category: "Security & Surveillance" | "Networking & IT" | "Smart Technology" | "Alarm & Safety"; summary: string; image: string; icon: LucideIcon; solutions: string[]; benefits: string[]; applications: string[]; faqs: { question: string; answer: string }[] }

export const services: Service[] = [
  { slug: "cctv-surveillance", title: "CCTV Surveillance", category: "Security & Surveillance", summary: "Professional surveillance solutions for homes, offices and commercial environments.", image: "/images/service-cctv.png", icon: Camera, solutions: ["IP CCTV systems", "Analog CCTV systems", "Indoor and outdoor cameras", "Recording and remote viewing"], benefits: ["Clear monitoring", "Requirement-based camera placement", "Remote access options", "Professional installation"], applications: ["Homes", "Offices", "Retail spaces", "Warehouses"], faqs: [{ question: "How many cameras do I need?", answer: "The right number depends on entrances, coverage areas and your site layout." }, { question: "Can I view cameras remotely?", answer: "Remote viewing options can be included where supported by the selected system." }] },
  { slug: "biometric-attendance", title: "Biometric Attendance", category: "Security & Surveillance", summary: "Practical fingerprint and face-attendance solutions for everyday operations.", image: "/images/EsslBio.png", icon: Fingerprint, solutions: ["Fingerprint attendance", "Face-recognition attendance", "Attendance reporting", "Device setup"], benefits: ["Accurate records", "Simpler attendance", "Controlled access options", "Scalable setup"], applications: ["Offices", "Schools", "Retail spaces", "Institutions"], faqs: [{ question: "Can biometric devices manage attendance?", answer: "Yes, suitable devices can be configured for attendance requirements." }, { question: "Do you provide installation?", answer: "We provide requirement-based recommendation and installation support." }] },
  { slug: "access-control-system", title: "Access Control System", category: "Security & Surveillance", summary: "Controlled entry solutions for secure, manageable premises.", image: "/images/EsslDoor_Lock.png", icon: ShieldCheck, solutions: ["Door access control", "RFID access", "Biometric access", "Entry management"], benefits: ["Controlled entry", "Clear access records", "Flexible credentials", "Professional installation"], applications: ["Offices", "Schools", "Retail spaces", "Institutions"], faqs: [{ question: "Can access be managed for multiple users?", answer: "Supported systems can be configured with different credentials and access rules." }, { question: "Can it work with biometrics?", answer: "Suitable access-control systems can include biometric entry options." }] },
  { slug: "networking-solutions", title: "Networking Solutions", category: "Networking & IT", summary: "Reliable LAN, WAN and structured cabling for connected business operations.", image: "/images/Networking_blog.png", icon: Network, solutions: ["LAN and WAN setup", "Structured cabling", "Routers and switches", "Network maintenance"], benefits: ["Cleaner connectivity", "Planned infrastructure", "Reliable coverage", "Support options"], applications: ["Offices", "Retail spaces", "Institutions", "Commercial sites"], faqs: [{ question: "Do you handle structured cabling?", answer: "Yes, networking solutions can include structured cabling planned around your site." }, { question: "Can an existing network be improved?", answer: "We can assess the current setup and recommend practical improvements." }] },
  { slug: "wifi-mesh-networking", title: "WiFi & Mesh Networking", category: "Networking & IT", summary: "Coverage-focused WiFi systems for homes, offices and multi-room environments.", image: "/images/Deco_M5.jpeg", icon: Radio, solutions: ["WiFi deployment", "Mesh WiFi", "Coverage optimisation", "Access point placement"], benefits: ["Better coverage", "Practical site planning", "Reduced dead zones", "Scalable expansion"], applications: ["Homes", "Offices", "Showrooms", "Multi-room sites"], faqs: [{ question: "What is mesh WiFi?", answer: "Mesh WiFi uses multiple connected points to extend coverage across a property." }, { question: "Will you check coverage first?", answer: "We recommend assessing the space and usage requirements first." }] },
  { slug: "it-support-amc", title: "IT Support & AMC", category: "Networking & IT", summary: "Preventive maintenance and technical assistance for security and IT systems.", image: "/images/AMC.png", icon: Wrench, solutions: ["Preventive maintenance", "System inspection", "Troubleshooting", "AMC planning"], benefits: ["Reduced downtime", "Planned maintenance", "Technical assistance", "Long-term support"], applications: ["Offices", "Retail spaces", "Homes", "Institutions"], faqs: [{ question: "What does AMC cover?", answer: "Coverage is defined around installed systems and agreed maintenance requirements." }, { question: "Can AMC include CCTV and networking?", answer: "Suitable AMC plans can cover multiple supported systems." }] },
  { slug: "server-networking-infrastructure", title: "Server & Networking Infrastructure", category: "Networking & IT", summary: "Structured infrastructure planning for business connectivity and core systems.", image: "/images/service-networking.jpg", icon: Server, solutions: ["Server setup", "Rack organisation", "Structured cabling", "Network infrastructure"], benefits: ["Organised infrastructure", "Better maintainability", "Planned deployment", "Professional handover"], applications: ["Offices", "Institutions", "Commercial sites", "Growing teams"], faqs: [{ question: "Do you provide server setup?", answer: "We provide requirement-based server and network infrastructure support." }, { question: "Can existing racks be organised?", answer: "A site assessment helps us recommend a practical approach." }] },
  { slug: "video-door-phone", title: "Video Door Phone", category: "Security & Surveillance", summary: "Visitor communication and entrance monitoring for homes and businesses.", image: "/images/VideoDoor_Bell.png", icon: Video, solutions: ["Video door phones", "Two-way communication", "Entrance monitoring", "Indoor display setup"], benefits: ["Visitor awareness", "Clear communication", "Practical entrance security", "Professional installation"], applications: ["Homes", "Apartments", "Offices", "Gated entries"], faqs: [{ question: "Can it be used in an office?", answer: "Yes, systems can be selected for home or business entrance needs." }, { question: "Do you provide installation?", answer: "Yes, we provide installation support based on the selected system." }] },
  { slug: "smart-door-locks", title: "Smart Door Locks", category: "Smart Technology", summary: "Keyless entry options for modern, controlled access.", image: "/images/EsslDoor_Lock.png", icon: KeyRound, solutions: ["Digital locks", "Keyless access", "Access credentials", "Entry management"], benefits: ["Convenient entry", "Controlled access", "Modern security", "Requirement-based selection"], applications: ["Homes", "Offices", "Rental properties", "Private rooms"], faqs: [{ question: "Which lock suits my door?", answer: "Door type, usage and access requirements determine the suitable option." }, { question: "Can multiple people have access?", answer: "Supported models can provide multiple access methods and user management." }] },
  { slug: "home-automation", title: "Home Automation", category: "Smart Technology", summary: "Connected home systems for practical control of lighting, security and devices.", image: "/images/service-automation.jpg", icon: House, solutions: ["Smart lighting", "Connected security", "Device control", "Automation planning"], benefits: ["Convenient control", "Connected systems", "Flexible expansion", "Professional setup"], applications: ["Homes", "Apartments", "Villas", "Smart spaces"], faqs: [{ question: "Can automation be added gradually?", answer: "Solutions can be planned in phases around your priorities." }, { question: "Can security be included?", answer: "Automation can be planned alongside compatible security systems." }] },
  { slug: "speaker-solutions", title: "Speaker Solutions", category: "Smart Technology", summary: "Professional audio and announcement systems for clear communication.", image: "/images/Ahuja_Speeker.webp", icon: Speaker, solutions: ["Commercial audio", "PA systems", "Announcement systems", "Speaker installation"], benefits: ["Clear communication", "Planned coverage", "Professional setup", "Expandable systems"], applications: ["Offices", "Schools", "Retail spaces", "Institutions"], faqs: [{ question: "Can speaker coverage be planned for large spaces?", answer: "Yes, we can recommend an approach based on the layout and intended use." }, { question: "Do you install PA systems?", answer: "We provide supported audio and announcement system installation." }] },
  { slug: "glass-break-alarm-system", title: "Glass Break Alarm System", category: "Alarm & Safety", summary: "Detection and alarm integration for glass-entry protection.", image: "/images/Glass_Break.jpg", icon: BellRing, solutions: ["Glass-break detection", "Alarm integration", "Security monitoring", "System planning"], benefits: ["Entry protection", "Fast alerting", "Integrated security", "Professional setup"], applications: ["Retail spaces", "Offices", "Showrooms", "Homes"], faqs: [{ question: "Can it integrate with an alarm system?", answer: "Suitable solutions can be planned with compatible alarm and security systems." }, { question: "Where is it useful?", answer: "It is useful where glass doors, windows or display areas need added entry protection." }] },
  { slug: "emergency-alarm-system", title: "Emergency Alarm System", category: "Alarm & Safety", summary: "Practical emergency alert and notification systems for safer premises.", image: "/images/EmergencyAlarm.jpeg", icon: BellRing, solutions: ["Emergency alert devices", "Alarm systems", "Notification planning", "Security integration"], benefits: ["Faster alerting", "Clear notification", "Site-focused planning", "Ongoing support options"], applications: ["Schools", "Offices", "Retail spaces", "Institutions"], faqs: [{ question: "Can an emergency alarm be tailored to our site?", answer: "Yes, solutions are planned around the site layout and notification needs." }, { question: "Can it work with other security systems?", answer: "Suitable alarm systems can be integrated with compatible security infrastructure." }] },
]

export const serviceBySlug = (slug: string) => services.find((service) => service.slug === slug)
