"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { button, Card, cc, CenterShell, Notice, time } from "./shared"
type Customer = { _id: string; name: string; phone: string; channel: string; optedOut: boolean; leadId?: string; updatedAt: string }
export default function Customers() {
  const [items, setItems] = useState<Customer[]>([]), [page, setPage] = useState(1), [total, setTotal] = useState(0), [error, setError] = useState(""), [loading, setLoading] = useState(true)
  useEffect(() => { const c = new AbortController(); setLoading(true); cc<{ items: Customer[]; total: number }>(`customers?page=${page}`, "GET", undefined, c.signal).then(r => { setItems(r.items); setTotal(r.total); setLoading(false) }).catch(e => { if (e.name !== "AbortError") { setError(e.message); setLoading(false) } }); return () => c.abort() }, [page])
  return <CenterShell title="Customers" subtitle="Verified channel identities linked to your existing leads, without matching people by display name.">{error && <Notice error={error}/>}<Card title="Customer directory">{loading ? <p role="status">Loading customers…</p> : !items.length ? <p className="py-8 text-sm text-muted-foreground">No channel customers yet. Customers appear when verified WhatsApp messages arrive.</p> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(c => <article key={c._id} className="min-w-0 rounded-xl border border-border p-4"><h3 className="break-words font-semibold">{c.name}</h3><p className="mt-2 text-sm">{c.phone}</p><p className="mt-1 text-xs text-muted-foreground">{c.channel} · {c.optedOut ? "Opted out" : "Service conversations"}</p><p className="mt-2 text-xs">Last activity: {time(c.updatedAt)}</p><div className="mt-3 flex flex-wrap gap-2">{c.leadId && <Link className={button} href={`/admin/leads/${c.leadId}`}>Open CRM Lead</Link>}<Link className={button} href="/admin/inbox">Open Inbox</Link></div></article>)}</div>}<div className="mt-5 flex items-center justify-between gap-3"><button className={button} disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</button><span className="text-xs">Page {page} · {total} customers</span><button className={button} disabled={page * 30 >= total} onClick={() => setPage(p => p + 1)}>Next</button></div></Card></CenterShell>
}
