"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { button, Card, cc, CenterShell, field, Notice } from "./shared"
import type { RequestItem } from "./types"
export default function Requests() {
  const [items, setItems] = useState<RequestItem[]>([]), [team, setTeam] = useState<{ _id: string; name: string }[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(""), [loading, setLoading] = useState(true)
  async function load() { setItems((await cc<{ items: RequestItem[] }>("requests")).items) }
  useEffect(() => { Promise.all([load(), cc<{ items: typeof team }>("team").then(r => setTeam(r.items))]).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [])
  return <CenterShell title="Customer Requests" subtitle="Confirm site visits, route support and plan follow-ups. A preferred time is not a confirmed appointment.">{error && <Notice error={error}/>}<Card title="Open requests">{loading ? <p role="status">Loading requests…</p> : !items.length ? <p className="py-6 text-sm text-muted-foreground">No open customer requests.</p> : <div className="grid min-w-0 gap-4 lg:grid-cols-2">{items.map(item => <form key={item._id} className="space-y-3 rounded-xl border border-border p-4" onSubmit={async e => { e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(item._id); setError(""); try { await cc(`requests/${item._id}`, "POST", { state: form.get("state"), assignedTo: form.get("assignedTo") || null, dueAt: form.get("dueAt") ? new Date(String(form.get("dueAt"))).toISOString() : null }); await load() } catch (e) { setError((e as Error).message) } finally { setBusy("") } }}><h3 className="font-semibold">{item.kind.replaceAll("_", " ")}</h3><p className="whitespace-pre-line break-words text-sm">{item.requirement}</p><p className="text-xs text-muted-foreground">Location: {item.location || "Not supplied"}<br/>Customer preference: {item.preferredWhen || "Not supplied"}</p><label className="grid gap-1 text-xs">Request state<select name="state" className={field} defaultValue={item.state}>{["REQUESTED", "PENDING_CONFIRMATION", "SCHEDULED", "ASSIGNED", "COMPLETED", "CANCELLED"].map(s => <option key={s}>{s}</option>)}</select></label><label className="grid gap-1 text-xs">Assigned team member<select name="assignedTo" className={field} defaultValue={item.assignedTo || ""}><option value="">Not assigned</option>{team.map(u => <option value={u._id} key={u._id}>{u.name}</option>)}</select></label><label className="grid gap-1 text-xs">Confirmed date / follow-up time (your local time)<input type="datetime-local" name="dueAt" className={field} defaultValue={item.dueAt ? new Date(new Date(item.dueAt).getTime() - new Date(item.dueAt).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ""}/></label><p className="text-xs text-muted-foreground">Scheduling requires a confirmed time and assignee. Saving does not send a customer message.</p><div className="flex flex-wrap gap-2"><button disabled={busy === item._id} className={button}>Save Request</button><Link className={button} href={`/admin/inbox?conversation=${item.conversationId}`}>View Conversation</Link></div></form>)}</div>}</Card></CenterShell>
}
