"use client"
import Link from "next/link"
import type { ReactNode } from "react"
export const field = "min-h-11 w-full min-w-0 rounded-xl border border-border bg-background px-3 py-2 text-sm text-foreground"
export const button = "inline-flex min-h-11 items-center justify-center rounded-xl border border-border bg-card px-3 py-2 text-sm font-medium text-foreground hover:bg-accent hover:text-accent-foreground disabled:opacity-50"
export function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="min-w-0 rounded-2xl border border-border bg-card p-4 sm:p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section> }
const errors: Record<string, string> = { META_NOT_CONFIGURED: "Configure the WhatsApp Cloud API connection in Integrations.", OPENAI_NOT_CONFIGURED: "Configure the OpenAI API key and model before generating replies.", CONVERSATION_CHANGED_RELOAD: "The conversation changed. Refresh it before trying again.", SEND_IN_PROGRESS_OR_CONVERSATION_CHANGED: "A message is sending or the conversation changed. Refresh and retry; takeover has not been applied yet.", APPROVED_TEMPLATE_REQUIRED: "The 24-hour customer-service window has closed. An approved WhatsApp template is required; free-form sending is blocked.", SEND_UNCERTAIN: "Delivery could not be confirmed. Check WhatsApp before sending again to avoid a duplicate.", CUSTOMER_OPTED_OUT: "This customer asked not to receive messages. Sending is paused.", AMBIGUOUS_LEAD_MATCH: "More than one lead matches this number. Review the existing CRM records before linking.", RATE_LIMITED: "Too many requests. Please try again shortly." }
export function Notice({ error }: { error: string }) { return <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm leading-6">{errors[error] || error.replaceAll("_", " ")}</p> }
export async function cc<T>(path: string, method = "GET", body?: unknown, signal?: AbortSignal): Promise<T> { const response = await fetch(`/api/admin/customer-center/${path}`, { method, cache: "no-store", signal, ...(body === undefined ? {} : { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "SERVICE_UNAVAILABLE"); return result }
export function CenterShell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <div className="min-w-0 space-y-5 text-foreground"><header><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-muted-foreground">VisionSecure Customer Center</p><h1 className="text-2xl font-bold sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{subtitle}</p></header><nav aria-label="Customer Center" className="flex flex-wrap gap-2">{[["/admin/inbox", "Inbox"], ["/admin/customer-center/customers", "Customers"], ["/admin/customer-center/requests", "Requests"], ["/admin/customer-center/knowledge", "AI Knowledge"], ["/admin/customer-center/agent", "AI Agent"], ["/admin/settings/integrations", "Integrations"]].map(([href, text]) => <Link className={button} href={href} key={href}>{text}</Link>)}</nav>{children}</div> }
export const time = (value?: string) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "short", timeStyle: "short" }) : "Not yet"
