"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import WhatsAppTestSend from "@/components/admin/whatsapp-test-send"
import GoogleConnectCard from "@/components/admin/website-analytics/google-connect-card"
import { button, Card, time } from "@/components/admin/customer-center/shared"

type Check = { status: string; error?: string; checkedAt?: string; lastSuccessAt?: string; latencyMs?: number }
type Summary = {
  checklist: { name: string; configured: boolean }[]; checks: Record<string, Check>; progress: { name: string; ready: boolean }[];
  appUrl: string; urlConflicts: string[]; model: string | null; ai: { missing: string[]; configured: boolean; mode: string };
  google: { status: string }; meta: { instagramAccountConfigured?: boolean; missing: string[]; status: string; businessNumber: string | null; webhook: string; lastWebhookAt?: string; lastInboundAt?: string; lastSendAt?: string };
  email: { configured: boolean; active: boolean }; webhookUrl: string | null;
}
function Portal({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} target="_blank" rel="noopener noreferrer" className={button}>{children}</a> }
function Status({ value }: { value: string }) {
  const style = /^(Connected|Passed|Healthy|Verified)$/.test(value) ? "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300" : /Failed|Error/.test(value) ? "bg-red-500/15 text-red-700 dark:text-red-300" : /Partial|Warning|Waiting|Configured/.test(value) ? "bg-amber-500/15 text-amber-800 dark:text-amber-300" : "bg-muted text-muted-foreground"
  return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${style}`}>{value}</span>
}
function Copy({ label, value }: { label: string; value: string }) {
  const [message, setMessage] = useState("")
  return <div className="min-w-0 space-y-2"><p>{label}</p><code className="block break-all rounded-lg bg-muted p-3 text-xs">{value}</code><button className={button} onClick={async () => { try { await navigator.clipboard.writeText(value); setMessage("Copied") } catch { setMessage("Select and copy the address above.") } }}>Copy {label}</button><span role="status" className="ml-2 text-xs">{message}</span></div>
}
function History({ check }: { check?: Check }) { return <div className="grid gap-2 text-xs text-muted-foreground"><p>Last verified: {time(check?.checkedAt)}</p><p>Last successful request: {time(check?.lastSuccessAt)}</p><p>Last sanitized error: {check?.error || "None recorded"}</p>{check?.latencyMs != null && <p>Latency: {check.latencyMs} ms</p>}</div> }
function Guide({ title, children }: { title: string; children: React.ReactNode }) { return <details className="rounded-xl border border-border p-4"><summary className="cursor-pointer font-medium">{title}</summary><div className="mt-4 space-y-4 text-sm leading-6">{children}</div></details> }
function GenerateKey() { return <code className="block break-all rounded-lg bg-muted p-3 text-xs">node -e &quot;console.log(require(&apos;crypto&apos;).randomBytes(32).toString(&apos;hex&apos;))&quot;</code> }
export default function IntegrationSetupCenter() {
  const [data, setData] = useState<Summary | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(""), [results, setResults] = useState<{ provider: string; status: string; error?: string }[]>([])
  async function load(signal?: AbortSignal) {
    const response = await fetch("/api/admin/integrations/health", { cache: "no-store", signal })
    const result = await response.json()
    if (!response.ok) throw new Error(response.status === 403 ? "Only a Super Admin can view setup diagnostics and manage integrations." : "Integration health is unavailable. Check your session and database connection.")
    setData(result)
  }
  useEffect(() => { const c = new AbortController(); load(c.signal).catch(e => { if (e.name !== "AbortError") setError(e.message) }); return () => c.abort() }, [])
  async function test(provider: string) {
    setBusy(provider); setError("")
    try {
      const response = await fetch("/api/admin/integrations/health", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider }) })
      const result = await response.json()
      if (!response.ok) throw new Error(result.error || "Test unavailable")
      setResults(result.results); await load()
    } catch (e) { setError((e as Error).message) } finally { setBusy("") }
  }
  const testButton = (provider: string, label: string) => <button className={button} disabled={!!busy} onClick={() => test(provider)}>{busy === provider ? "Checking…" : label}</button>
  return <div className="min-w-0 space-y-6 text-foreground"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">VisionSecure</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Integration Setup Center</h1><p className="mt-2 text-sm text-muted-foreground">Website services, customer messaging and your AI assistant.</p></div>{data && testButton("all", "Test All Integrations")}</header>
    {error && <p role="alert" className="break-words rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm">{error}</p>}
    {!data ? !error && <p role="status">Loading setup diagnostics…</p> : <>
      {!!results.length && <div role="status" className="flex flex-wrap gap-3 rounded-xl bg-muted p-4">{results.map(r => <p className="text-sm" key={r.provider}>{r.provider}: <Status value={r.status}/>{r.error && <span className="block break-all text-xs">{r.error}</span>}</p>)}</div>}
      <Card title="Setup progress"><p className="mb-3 text-lg font-semibold">{data.progress.filter(p => p.ready).length} / {data.progress.length} integrations ready</p><div className="flex flex-wrap gap-3">{data.progress.map(p => <span key={p.name} className="text-sm">{p.name}: <Status value={p.ready ? "Connected" : "Not ready"}/></span>)}</div><p className="mt-3 text-xs text-muted-foreground">Optional channels do not block the application. Configuration alone does not verify a connection.</p></Card>
      <h2 className="text-lg font-semibold">Website & Google</h2><GoogleConnectCard key={data.checks.google?.checkedAt} onChanged={load}/>
      <Guide title="How to connect Google"><Portal href="https://console.cloud.google.com/apis/credentials">Open Google Cloud</Portal><ol className="list-inside list-decimal space-y-2"><li>Select a project and enable Google Analytics Data API and Search Console API.</li><li>Configure the consent screen. Create an OAuth Web application and add both callbacks below.</li><li>Set GOOGLE_TOKEN_ENCRYPTION_KEY on the server. Save Client ID / Client Secret in the existing encrypted configuration or deployment settings.</li><li>Save, sign in with Google, then test the connection.</li></ol><Copy label="local callback" value="http://localhost:3000/api/admin/integrations/google/callback"/><Copy label="production callback" value="https://visionsecuretech.in/api/admin/integrations/google/callback"/><Copy label="active callback" value={`${data.appUrl}/api/admin/integrations/google/callback`}/><p>Existing tokens encrypted using an auth-secret fallback require reconnection after migration.</p><Guide title="How to Generate Key"><p>Run locally and store the result as GOOGLE_TOKEN_ENCRYPTION_KEY in deployment secrets.</p><GenerateKey/></Guide></Guide>
      <h2 className="text-lg font-semibold">Customer Messaging</h2><Card title="Meta Customer Messaging"><div className="space-y-4 text-sm"><div className="flex flex-wrap gap-3"><span>WhatsApp: <Status value={data.meta.status}/></span><span>Instagram: <Status value="Not connected"/></span><span>Facebook Messenger: <Status value="Not connected"/></span></div><p>Business number: {data.meta.businessNumber || "Not verified"}</p><div className="grid gap-2 sm:grid-cols-2">{data.checklist.filter(c => c.name.startsWith("META_")).map(c => <p className="break-all" key={c.name}>{c.name}: <Status value={c.configured ? "Configured" : "Missing"}/></p>)}</div><p>Webhook: <Status value={data.meta.webhook}/></p><p>Last webhook: {time(data.meta.lastWebhookAt)}<br/>Last incoming message: {time(data.meta.lastInboundAt)}<br/>Last successful send: {time(data.meta.lastSendAt)}</p><History check={data.checks.meta}/><div className="flex flex-wrap gap-2"><Portal href="https://developers.facebook.com/apps/">Open Meta Developers</Portal><Portal href="https://business.facebook.com/">Open Meta Business</Portal>{testButton("meta", "Test Meta Configuration")}</div>
      <Guide title="Setup WhatsApp"><ol className="list-inside list-decimal space-y-2"><li>Create or select your VisionSecure Meta app.</li><li>Add WhatsApp and connect the appropriate business assets.</li><li>Register your business number and obtain its Phone Number ID.</li><li>Store META_APP_SECRET, META_VERIFY_TOKEN, META_ACCESS_TOKEN and META_PHONE_NUMBER_ID in server deployment secrets.</li><li>Set META_GRAPH_VERSION explicitly to a currently supported version for your app, in vXX.0 format.</li><li>Configure the public HTTPS webhook and subscribe to messaging fields using the current official guide.</li><li>Verify the webhook, send an inbound message from your own test phone, then take over that conversation in Inbox to test a reply.</li></ol>{data.webhookUrl ? <Copy label="WhatsApp webhook URL" value={data.webhookUrl}/> : <p>Local development requires a secure public HTTPS tunnel to /api/webhooks/whatsapp. Meta cannot reach localhost. Production endpoint: https://visionsecuretech.in/api/webhooks/whatsapp</p>}<p>META_VERIFY_TOKEN is a VisionSecure-created random secret for webhook verification, not the App Secret, access token or WhatsApp OTP. Generate locally:</p><GenerateKey/><Portal href="https://developers.facebook.com/documentation/business-messaging/whatsapp/">Official WhatsApp setup guide</Portal></Guide>
      <Guide title="WhatsApp Diagnostics"><WhatsAppTestSend/><p>The API test reads registered phone metadata. Webhook verification and incoming events are tracked separately. Outbound capability remains unverified until an explicit send succeeds.</p><p>Use your own test phone to start a conversation. Select it in Inbox, take over, review the recipient and explicitly send. Test All never sends messages.</p><Link className={button} href="/admin/inbox">Open Inbox for test reply</Link></Guide>
      <Guide title="Setup Instagram"><p>Account ID: {data.meta.instagramAccountConfigured ? "Configured; API access not verified" : "Missing"}</p><p>Follow the current official guide for your Instagram Professional account and chosen login flow. Complete the required business assets, app permissions, access review and signed webhook verification. The INSTAGRAM channel shares the existing Conversation, Message, Inbox, customer resolver, AI and knowledge base. Its adapter is not active yet.</p><Portal href="https://developers.facebook.com/docs/instagram-platform/">Official Instagram setup</Portal></Guide>
      <Guide title="Setup Facebook Messenger"><p>Connect the appropriate Page and app using the current official guide. Complete required permissions, access review and webhook verification. The FACEBOOK channel is reserved in the same Inbox and CRM; its adapter is not active yet.</p><Portal href="https://developers.facebook.com/docs/messenger-platform/">Official Messenger setup</Portal></Guide></div></Card>
      <Card title="Website Chat"><Status value="Not configured"/><p className="mt-3 text-sm text-muted-foreground">The WEBSITE channel is reserved for the shared Inbox, AI, knowledge base and human takeover. A public widget is not active.</p></Card>
      <h2 className="text-lg font-semibold">AI</h2><Card title="OpenAI AI Assistant"><div className="space-y-4 text-sm"><Status value={!data.ai.configured ? "Missing" : data.checks.ai?.status === "Passed" ? "Connected" : data.checks.ai?.status === "Failed" ? "Error" : "Configured"}/><p>Model: {data.model || "Not configured"}<br/>AI mode: {data.ai.mode}</p><p>Understand before selling. Use published knowledge, ask 1–2 useful questions and hand off unsupported promises to a person.</p><History check={data.checks.ai}/>{!!data.ai.missing.length && <p className="break-words">Required: {data.ai.missing.join(", ")}</p>}<div className="flex flex-wrap gap-2">{testButton("ai", "Test AI Connection")}<Portal href="https://platform.openai.com/api-keys">Open OpenAI API Keys</Portal></div><Guide title="OpenAI Setup Guide"><ol className="list-inside list-decimal space-y-2"><li>Open OpenAI Platform; create or select a VisionSecure API project.</li><li>Create a NEW project API key.</li><li>Store it as OPENAI_API_KEY in server deployment settings.</li><li>Set OPENAI_MODEL to a model supporting Responses and structured outputs.</li><li>Redeploy if required, return here and click Test AI Connection.</li></ol><p>The test uses a tiny synthetic prompt without customer data. It never changes AI mode. DRAFT remains the default; AUTO requires an explicit Super Admin change.</p><p>Never paste production API keys into AI coding prompts. Never store them in source, NEXT_PUBLIC_*, localStorage or sessionStorage.</p></Guide></div></Card>
      <h2 className="text-lg font-semibold">Email & Notifications</h2><Card title="Email delivery"><div className="space-y-4 text-sm"><Status value={data.checks.email?.status === "Failed" ? "Error" : data.checks.email?.status === "Passed" ? "Connected" : data.email.configured ? "Configured" : "Missing"}/><p>Notification service: {data.email.active ? "Active" : "Not active in encrypted email configuration"}. Connectivity does not activate delivery.</p><History check={data.checks.email}/><div className="flex flex-wrap gap-2">{testButton("email", "Test Email Connectivity")}<Link className={button} href="/admin/settings/email">Configure Email</Link><Portal href="https://mailadmin.zoho.in/">Open Zoho Admin</Portal></div><p>Connectivity tests authenticate without sending email. Prefer SMTP_PASS and MAIL_FROM; legacy SMTP_PASSWORD and EMAIL_FROM remain supported.</p></div></Card>
      <h2 className="text-lg font-semibold">System Health</h2><Card title="Integration Health"><div className="grid gap-3 text-sm sm:grid-cols-2"><p>Google: <Status value={data.google.status}/></p><p>OpenAI: <Status value={data.checks.ai?.status === "Passed" && data.ai.configured ? "Connected" : "Missing"}/></p><p>WhatsApp: <Status value={data.meta.status}/></p><p>Instagram: <Status value="Not connected"/></p><p>Facebook: <Status value="Not connected"/></p><p>Email: <Status value={data.checks.email?.status === "Passed" ? "Connected" : data.checks.email?.status === "Failed" ? "Error" : data.email.configured ? "Configured" : "Missing"}/></p><p>Database: <Status value={data.checks.database?.status === "Passed" ? "Healthy" : data.checks.database?.status === "Failed" ? "Error" : "Not tested"}/></p></div><div className="mt-4 space-y-3">{testButton("database", "Test Database")}<History check={data.checks.database}/></div></Card>
      <Card title="Security Setup Checklist"><div className="grid gap-3 text-sm sm:grid-cols-2">{data.checklist.map(c => <p className="break-words" key={c.name}>{c.name}: <Status value={c.configured ? "Configured" : "Missing"}/></p>)}</div><p className="mt-4 text-sm text-muted-foreground">Rotate credentials previously shared in prompts or logs. Re-encrypt stored data before retiring an encryption key.</p></Card>
      <Guide title="Environment setup"><Copy label="Website URL" value={data.appUrl}/><Copy label="Search Console property URL" value="https://visionsecuretech.in/"/><p>Set AUTH_URL, NEXTAUTH_URL, NEXT_PUBLIC_APP_URL and NEXT_PUBLIC_SITE_URL to the same origin: http://localhost:3000 locally; https://visionsecuretech.in in production. Keep Search Console on the verified business website.</p>{!!data.urlConflicts.length && <p role="alert">Conflicting URL settings: {data.urlConflicts.join(", ")}</p>}</Guide>
    </>}
  </div>
}
