"use client"
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, Pie, PieChart, Cell } from "recharts"
import { useState } from "react"
import { useReducedMotion } from "framer-motion"
import type { DashboardData } from "./types"
const tooltip={background:"var(--popover)",color:"var(--popover-foreground)",border:"1px solid var(--border)",borderRadius:12}
export function TrendChart({trend}:{trend:NonNullable<DashboardData["trend"]>}){
 const reduced=useReducedMotion()
 return <><p className="mt-2 text-sm text-muted-foreground">{trend.current} leads / {trend.previous} in the previous period. <span className="font-semibold text-foreground">{trend.change===null?"No previous data":`${trend.change>0?"+":""}${trend.change}%`}</span></p><div role="img" aria-label={`Lead trend: ${trend.current} leads in this period, ${trend.previous} in previous period`} className="mt-4 h-56 min-w-0"><ResponsiveContainer width="100%" height="100%"><AreaChart accessibilityLayer data={trend.rows} margin={{left:-20,right:10}}><defs><linearGradient id="dashboard-trend" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--highlight)" stopOpacity={0.3}/><stop offset="100%" stopColor="var(--highlight)" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 3"/><XAxis dataKey="label" minTickGap={35} tick={{fill:"var(--muted-foreground)",fontSize:11}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fill:"var(--muted-foreground)",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} labelFormatter={(_,payload)=>payload?.[0]?.payload?.date || ""}/><Area name="New leads" dataKey="total" stroke="var(--highlight)" fill="url(#dashboard-trend)" strokeWidth={2} isAnimationActive={!reduced}/></AreaChart></ResponsiveContainer></div><details className="mt-2 text-xs text-muted-foreground"><summary className="cursor-pointer py-2">View chart data</summary><div className="max-h-40 overflow-auto">{trend.rows.map(row=><p key={row.date} className="flex justify-between py-1"><span>{row.date}</span><span>{row.total} leads</span></p>)}</div></details></>
}
export function ServiceDemand({metrics}:{metrics:Pick<NonNullable<DashboardData["metrics"]>, "total" | "services">}){
 const [active, setActive] = useState<number | null>(null)
 const reduced=useReducedMotion();const colors=["var(--chart-1)","var(--chart-2)","var(--chart-3)","var(--chart-4)","var(--chart-5)","var(--muted-foreground)"]
 const rows=metrics.services.slice(0,5).map(row=>({name:row._id||"General enquiry",value:row.total})); const other=metrics.services.slice(5).reduce((sum,row)=>sum+row.total,0);if(other)rows.push({name:"Other services",value:other})
 if(!metrics.total)return <p className="py-8 text-sm text-muted-foreground">Service insights will appear as enquiries arrive.</p>
 return <div className="mt-4 grid items-center gap-4 sm:grid-cols-[180px_1fr]"><div className="relative h-44" role="img" aria-label={`Service demand across ${metrics.total} leads`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="value" nameKey="name" innerRadius={52} outerRadius={75} paddingAngle={2} stroke="var(--card)" isAnimationActive={!reduced} onMouseEnter={(_, index) => setActive(index)} onMouseLeave={() => setActive(null)}>{rows.map((row,index)=><Cell key={row.name} fill={colors[index]}/>)}</Pie></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-2xl">{metrics.total}</strong><span className="text-xs text-muted-foreground">Total leads</span></div></div><div className="min-w-0"><div role="status" aria-live="polite" className="mb-3 min-h-16 rounded-xl border border-border bg-muted/30 p-3 text-sm" style={active !== null ? { borderLeft: `4px solid ${colors[active]}` } : undefined}>{active !== null && rows[active] ? <><p className="flex items-center gap-2 font-semibold"><span className="h-3 w-3 shrink-0 rounded-full" style={{background:colors[active]}}/>{rows[active].name}</p><p className="mt-1 text-xs text-muted-foreground">{rows[active].value} leads / {Math.round(rows[active].value / metrics.total * 100)}% of all leads</p></> : <p className="text-xs leading-5 text-muted-foreground">Hover a chart segment or select a service to see its demand. The center shows all leads.</p>}</div><ul className="space-y-2">{rows.map((row,index)=><li key={row.name}><button type="button" onMouseEnter={() => setActive(index)} onMouseLeave={() => setActive(null)} onFocus={() => setActive(index)} onBlur={() => setActive(null)} onClick={() => setActive(index)} className="flex min-h-9 w-full items-center gap-2 rounded-lg px-2 text-left text-sm" style={{background: active === index ? "var(--muted)" : undefined}}><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{background:colors[index]}}/><span className="min-w-0 flex-1 break-words">{row.name}</span><strong>{row.value}</strong><span className="text-xs text-muted-foreground">{Math.round(row.value/metrics.total*100)}%</span></button></li>)}</ul></div></div>
}
