"use client"
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, Pie, PieChart, Cell } from "recharts"
import { useReducedMotion } from "framer-motion"
import type { DashboardData } from "./types"
const tooltip={background:"var(--popover)",color:"var(--popover-foreground)",border:"1px solid var(--border)",borderRadius:12}
export function TrendChart({trend}:{trend:NonNullable<DashboardData["trend"]>}){
 const reduced=useReducedMotion()
 return <><p className="mt-2 text-sm text-muted-foreground">{trend.current} leads / {trend.previous} in the previous period. <span className="font-semibold text-foreground">{trend.change===null?"No previous data":`${trend.change>0?"+":""}${trend.change}%`}</span></p><div role="img" aria-label={`Lead trend: ${trend.current} leads in this period, ${trend.previous} in previous period`} className="mt-4 h-56 min-w-0"><ResponsiveContainer width="100%" height="100%"><AreaChart accessibilityLayer data={trend.rows} margin={{left:-20,right:10}}><defs><linearGradient id="dashboard-trend" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--highlight)" stopOpacity={0.3}/><stop offset="100%" stopColor="var(--highlight)" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 3"/><XAxis dataKey="label" minTickGap={35} tick={{fill:"var(--muted-foreground)",fontSize:11}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fill:"var(--muted-foreground)",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} labelFormatter={(_,payload)=>payload?.[0]?.payload?.date || ""}/><Area name="New leads" dataKey="total" stroke="var(--highlight)" fill="url(#dashboard-trend)" strokeWidth={2} isAnimationActive={!reduced}/></AreaChart></ResponsiveContainer></div><details className="mt-2 text-xs text-muted-foreground"><summary className="cursor-pointer py-2">View chart data</summary><div className="max-h-40 overflow-auto">{trend.rows.map(row=><p key={row.date} className="flex justify-between py-1"><span>{row.date}</span><span>{row.total} leads</span></p>)}</div></details></>
}
export function ServiceDemand({metrics}:{metrics:NonNullable<DashboardData["metrics"]>}){
 const reduced=useReducedMotion();const colors=["var(--chart-1)","var(--chart-2)","var(--chart-3)","var(--chart-4)","var(--chart-5)","var(--muted-foreground)"]
 const rows=metrics.services.slice(0,5).map(row=>({name:row._id||"General enquiry",value:row.total})); const other=metrics.services.slice(5).reduce((sum,row)=>sum+row.total,0);if(other)rows.push({name:"Other services",value:other})
 if(!metrics.total)return <p className="py-8 text-sm text-muted-foreground">Service insights will appear as enquiries arrive.</p>
 return <div className="mt-4 grid items-center gap-4 sm:grid-cols-[180px_1fr]"><div className="relative h-44" role="img" aria-label={`Service demand across ${metrics.total} leads`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="value" nameKey="name" innerRadius={52} outerRadius={75} paddingAngle={2} stroke="var(--card)" isAnimationActive={!reduced}>{rows.map((row,index)=><Cell key={row.name} fill={colors[index]}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-2xl">{metrics.total}</strong><span className="text-xs text-muted-foreground">Total leads</span></div></div><ul className="space-y-3">{rows.map((row,index)=><li key={row.name} className="flex items-center gap-2 text-sm"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{background:colors[index]}}/><span className="min-w-0 flex-1 break-words">{row.name}</span><strong>{row.value}</strong><span className="text-xs text-muted-foreground">{Math.round(row.value/metrics.total*100)}%</span></li>)}</ul></div>
}
