"use client"
import { useCallback, useEffect, useRef, useState } from "react"
import Link from "next/link"
import { motion, useReducedMotion } from "framer-motion"
import { Activity, ArrowRight, CalendarDays, RefreshCw, Users, UserPlus, CheckCircle2, Clock3 } from "lucide-react"
import { ExpandableSection } from "./expandable-section"
import { LiveHeader, RelativeTime } from "./live-header"
import { StatusBadge } from "./status-badge"
import { RecentLeads } from "./recent-leads"
import { ServiceDemand, TrendChart } from "./charts"
import type { DashboardData } from "./types"
const card="min-w-0 rounded-2xl border border-border bg-card p-4 shadow-sm sm:p-5"
const button="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-semibold transition hover:bg-muted disabled:opacity-50"
const statusHref=(status:string)=>`/admin/leads?status=${encodeURIComponent(status)}`
export default function DashboardOverview(){
 const [data,setData]=useState<DashboardData|null>(null),[days,setDays]=useState(30),[busy,setBusy]=useState(false),[error,setError]=useState("")
 const inFlight=useRef<AbortController|null>(null);const reduced=useReducedMotion()
 const load=useCallback(async()=>{
   inFlight.current?.abort();const controller=new AbortController();inFlight.current=controller;setBusy(true)
   try{const response=await fetch(`/api/admin/dashboard?days=${days}`,{cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error(response.status===401||response.status===403?"Your session needs attention. Please sign in again.":"Unable to refresh dashboard.");const next=await response.json();if(!controller.signal.aborted){setData(next);setError("")}}
   catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Unable to refresh dashboard.")}
   finally{if(!controller.signal.aborted)setBusy(false)}
 },[days])
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load()},60000);const focus=()=>{if(document.visibilityState==="visible")void load()};document.addEventListener("visibilitychange",focus);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",focus);inFlight.current?.abort()}},[load])
 const retry=<button className={button} disabled={busy} onClick={()=>void load()}>Retry</button>
 const failed=(label:string)=><div role="alert" className="flex flex-wrap items-center gap-3 py-6 text-sm text-muted-foreground">Unable to load {label}. {retry}</div>
 if(!data&&!error)return <div role="status" aria-label="Loading dashboard" className="space-y-4"><div className="h-32 animate-pulse rounded-2xl bg-muted"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="h-28 animate-pulse rounded-2xl bg-muted"/>)}</div><div className="h-72 animate-pulse rounded-2xl bg-muted"/></div>
 const m=data?.metrics
 return <div className="mx-auto max-w-[1600px] space-y-5 pb-6 text-foreground">
   <header className={card}><LiveHeader name={data?.displayName||"Admin"}/><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-3"><p className="text-xs text-muted-foreground">{data?`Last updated ${new Date(data.updatedAt).toLocaleTimeString()} / Business dates: India (IST)` : "Secure business overview"}</p><div className="flex flex-wrap gap-2"><button aria-label={busy?"Refreshing dashboard":"Refresh dashboard"} title="Refresh dashboard" className={`${button} w-11 px-0`} disabled={busy} onClick={()=>void load()}><RefreshCw aria-hidden="true" size={18} className={busy?"animate-spin":""}/></button><Link href="/contact#contact-section" aria-label="Add New Lead" title="Add New Lead" className={`${button} w-11 border-transparent bg-accent px-0 text-accent-foreground hover:bg-brand-hover`}><UserPlus aria-hidden="true" size={18}/></Link></div></div></header>
   {error&&<p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error} {data&&"Showing the last loaded data."} <button className="ml-2 underline" onClick={()=>void load()}>Retry</button></p>}
   {data&&<>
   {m?<section aria-label="Business KPIs" className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">{[
    {label:"Total leads",value:m.total,detail:`${m.active} active in pipeline`,href:"/admin/leads",icon:Users},
    {label:"New leads today",value:m.today,detail:m.yesterday?`${m.yesterday} yesterday`:"No previous data",href:"/admin/leads?filter=today",icon:UserPlus},
    {label:"Follow-ups today",value:m.due,detail:`${m.overdue} overdue from earlier days`,href:"/admin/leads?filter=due",icon:Clock3},
    {label:"Won / installed",value:m.converted,detail:`${m.conversionRate}% conversion overall`,href:"/admin/leads?filter=won",icon:CheckCircle2},
    {label:"Quotations sent",value:m.quotations,detail:"Review customer responses",href:statusHref("Quotation Sent"),icon:Activity},
    {label:"Installations",value:m.installations,detail:"Scheduled stage / all dates",href:statusHref("Installation Scheduled"),icon:CalendarDays},
   ].map((item,index)=><motion.div key={item.label} initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.25,delay:reduced?0:index*.04}}><Link href={item.href} className={`${card} block h-full transition hover:-translate-y-0.5 hover:border-accent`}><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium text-muted-foreground sm:text-sm">{item.label}</p><span className="rounded-lg bg-accent/10 p-2 text-brand-green"><item.icon size={18}/></span></div><p className="mt-2 text-3xl font-bold tabular-nums">{item.value}</p><p className="mt-2 text-xs text-muted-foreground">{item.detail}</p></Link></motion.div>)}</section>:failed("business metrics")}
   <section className="grid gap-5 xl:grid-cols-[1.2fr_1fr]">
    <div className={card}><h2 className="text-lg font-bold">Today's Action Center</h2><p className="mt-1 text-xs text-muted-foreground">{m?`${m.attention} distinct leads need attention. Categories may overlap.`:"Action counts unavailable."}</p>{m?<div className="mt-4 grid grid-cols-2 gap-3">{[
      ["Overdue follow-ups",m.overdue,"/admin/leads?filter=overdue","text-destructive bg-destructive/5"],
      ["Follow-ups today",m.due,"/admin/leads?filter=due","text-warning bg-warning/5"],
      ["New leads",m.new,statusHref("New"),"text-highlight-ink bg-highlight/5"],
      ["Quotations sent",m.quotations,statusHref("Quotation Sent"),"text-status-purple bg-status-purple/5"],
    ].map(([label,value,href,tone])=><Link key={label} href={String(href)} className={`rounded-xl border border-border p-3 transition hover:-translate-y-0.5 ${tone}`}><div className="flex items-center justify-between"><strong className="text-2xl">{value}</strong><ArrowRight size={15}/></div><p className="mt-1 text-xs font-medium">{label}</p></Link>)}</div>:failed("action center")}</div>
    <div className={card}><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Today's schedule</h2><CalendarDays size={18} className="text-brand-green"/></div><p className="mt-1 text-xs text-muted-foreground">Scheduled follow-ups / India time (IST)</p>{data.schedule?<>{!data.schedule.length?<p className="py-8 text-sm text-muted-foreground">No follow-ups scheduled today. You're all caught up.</p>:<ol className="mt-3 max-h-60 overflow-y-auto divide-y divide-border">{data.schedule.map(lead=><li key={lead._id}><Link href={`/admin/leads/${lead._id}`} className="flex gap-3 rounded-lg py-3 hover:bg-muted"><time className="w-20 shrink-0 text-xs font-semibold text-brand-green">{new Date(lead.followUpDate!).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata",hour:"2-digit",minute:"2-digit"})}</time><div className="min-w-0"><p className="truncate text-sm font-semibold">{lead.name}</p><p className="text-xs text-muted-foreground">{lead.service||"General enquiry"} / {lead.assignedTo?.name||"Unassigned"}</p><p className="mt-1 text-xs text-warning">Follow-up scheduled</p></div></Link></li>)}</ol>}{m&&m.due>20&&<Link href="/admin/leads?filter=due" className="text-xs underline">View all {m.due} scheduled follow-ups</Link>}</>:failed("schedule")}</div>
   </section>
   <nav aria-label="Quick actions" className="flex flex-wrap gap-2">{[["All leads","/admin/leads"],["Schedule follow-up","/admin/leads?filter=active"],["Manage users","/admin/users"],["Analytics","/admin/analytics"],["Email settings","/admin/settings/email"]].map(([label,href])=><Link key={href} href={href} className={`${button} bg-card`}>{label}<ArrowRight size={14}/></Link>)}</nav>
   <section className="grid gap-5 lg:grid-cols-2"><ExpandableSection title="Lead pipeline" description="Current stages / share of all leads">{m?<div className="mt-4 space-y-3">{["New","In Discussion","Follow-Up","Quotation Sent","Installation Scheduled","Installed Successfully","Converted","Cancelled","Closed"].map(status=>{const count=m.pipeline.find(row=>row._id===status)?.total||0;const percent=m.total?Math.round(count/m.total*100):0;return <Link key={status} href={statusHref(status)} className="block rounded-lg p-1 hover:bg-muted"><div className="mb-1 flex items-center justify-between gap-2 text-xs"><StatusBadge status={status}/><span>{count} / {percent}%</span></div><div className="h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-highlight" style={{width:`${percent}%`}}/></div></Link>})}</div>:failed("pipeline")}</ExpandableSection><div className={card}><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold">Lead trend</h2><label className="text-xs">Period <select aria-label="Trend period" className="ml-1 min-h-11 rounded-lg border border-border bg-background px-2" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(day=><option key={day} value={day}>Last {day} days</option>)}</select></label></div>{data.trend?<TrendChart trend={data.trend}/>:failed("lead trend")}</div></section>
   <section className="grid gap-5 lg:grid-cols-2"><div className={card}><h2 className="text-lg font-bold">Service demand</h2><p className="mt-1 text-xs text-muted-foreground">Enquiry volume across all leads</p>{m?<ServiceDemand metrics={m}/>:failed("service demand")}</div><div className={card}><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-bold">User management</h2><Link href="/admin/users" className="text-sm text-brand-green">Manage users</Link></div>{data.users?<><div className="mt-4 grid grid-cols-3 gap-2">{[["Total",data.users.total],["Active",data.users.active],["Inactive",data.users.total-data.users.active]].map(([label,value])=><div key={label} className="rounded-xl bg-muted/60 p-3"><strong className="text-2xl">{value}</strong><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div><ul className="mt-4 space-y-2">{data.users.roles.map(row=><li key={row.role} className="flex justify-between text-sm"><span className="capitalize text-muted-foreground">{row.role.replaceAll("_"," ")}</span><strong>{row.total}</strong></li>)}</ul></>:failed("team summary")}</div></section>
   <ExpandableSection title="5 recent leads" description="Newest enquiries first. Use the Action Center for priority work."><Link className="inline-flex min-h-11 items-center text-sm text-brand-green" href="/admin/leads">View all leads <ArrowRight size={14}/></Link>{data.leads?<RecentLeads leads={data.leads}/>:failed("recent leads")}</ExpandableSection>
   <ExpandableSection title="Recent activity"><Link className="inline-flex min-h-11 items-center text-sm text-brand-green" href="/admin/activity-logs">View all activity <ArrowRight size={14}/></Link>{data.activity?<>{!data.activity.length?<p className="py-8 text-sm text-muted-foreground">No activity recorded yet.</p>:<ol className="mt-3 divide-y divide-border">{data.activity.map(item=><li key={item._id} className="flex items-start gap-3 py-3"><span className="rounded-lg bg-muted p-2"><Activity size={16}/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold capitalize">{item.action.toLowerCase().replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted-foreground">{item.userId?.name||"Deleted user"} / {item.resourceType} / <RelativeTime value={item.createdAt}/></p>{item.resourceType==="Lead"&&item.resourceId&&<Link href={`/admin/leads/${item.resourceId}`} className="text-xs text-brand-green">Open lead</Link>}</div><span className={`text-xs ${item.status==="failed"?"text-destructive":"text-brand-green"}`}>{item.status}</span></li>)}</ol>}</>:failed("recent activity")}</ExpandableSection>
   </>}
 </div>
}
