import Link from "next/link"
import { FaWhatsapp } from "react-icons/fa"
import { Phone, ArrowUpRight } from "lucide-react"
import { StatusBadge } from "./status-badge"
import type { DashboardLead } from "./types"
export function RecentLeads({leads}:{leads:DashboardLead[]}) {
 const actions=(lead:DashboardLead)=>{const phone=lead.phone.replace(/\D/g, "");return <div className="flex flex-wrap items-center gap-2"><Link aria-label={`Open ${lead.name}`} title={`Open ${lead.name}`} className="inline-flex h-11 w-11 items-center justify-center rounded-lg bg-accent text-accent-foreground transition hover:bg-brand-hover" href={`/admin/leads/${lead._id}`}><ArrowUpRight aria-hidden="true" size={18}/></Link>{phone && <><a className="inline-flex h-11 w-11 items-center justify-center rounded-lg border border-border" href={`tel:+${phone.length===10?"91":""}${phone}`} aria-label={`Call ${lead.name}`}><Phone size={16}/></a><a aria-label={`WhatsApp ${lead.name}`} title={`WhatsApp ${lead.name}`} className="inline-flex h-11 w-11 items-center justify-center rounded-lg border border-border text-[#25D366] transition hover:bg-muted" href={`https://wa.me/${phone.length===10?"91":""}${phone}`} target="_blank" rel="noopener noreferrer"><FaWhatsapp aria-hidden="true" size={20}/></a></>}</div>}
 if(!leads.length)return <p className="py-10 text-center text-muted-foreground">No leads yet. New enquiries will appear here.</p>
 return <><div className="mt-4 space-y-3 md:hidden">{leads.slice(0,5).map(lead=><article key={lead._id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="min-w-0 break-words font-semibold">{lead.name}</h3><StatusBadge status={lead.status}/></div><p className="mt-2 text-sm text-muted-foreground">{lead.service || "General enquiry"} / {lead.source || "Not recorded"}</p><p className="my-3 text-xs text-muted-foreground">Assigned: {lead.assignedTo?.name || "Unassigned"}<br/>Follow-up: {lead.followUpDate ? new Date(lead.followUpDate).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})+" IST":"Not scheduled"}<br/>Received: {new Date(lead.createdAt).toLocaleDateString("en-IN")}</p>{actions(lead)}</article>)}</div><div className="mt-4 hidden overflow-x-auto md:block"><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground">{["Customer","Service / source","Status","Assigned","Next follow-up (IST)","Received","Action"].map(label=><th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{leads.slice(0,5).map(lead=><tr key={lead._id} className="border-b border-border last:border-0 hover:bg-muted/40"><td className="px-3 py-4 font-semibold">{lead.name}<span className="mt-1 block text-xs font-normal text-muted-foreground">{lead.phone}</span></td><td className="px-3 py-4">{lead.service || "General enquiry"}<span className="block text-xs text-muted-foreground">{lead.source || "Not recorded"}</span></td><td className="px-3 py-4"><StatusBadge status={lead.status}/></td><td className="px-3 py-4">{lead.assignedTo?.name || "Unassigned"}</td><td className="px-3 py-4 text-xs">{lead.followUpDate ? new Date(lead.followUpDate).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"}):"Not scheduled"}</td><td className="px-3 py-4 text-xs">{new Date(lead.createdAt).toLocaleDateString("en-IN")}</td><td className="px-3 py-4">{actions(lead)}</td></tr>)}</tbody></table></div></>
}
